---
language: go
go:
  - 1.9
install:
  - go get github.com/tools/godep
  - godep restore
branches:
  only:
  - master
script:
  - go build ./...

      after_success:
        - bash <(curl -s https://codecov.io/bash)